name: onthewaytravel groups
favicon: null
layout_spectrum: 0.961720343446359
typography_spectrum: 0.9345356633421034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.741961344378069
  lightness: 0.7709882156923413
  saturation: 0.9885732980910689
  rhythmicContrast: 0.15024566720239818
purpose: []
